version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      packages:
        - sphinx
        - nbsphinx
        - myst-parser
        - ipython
        - ipykernel

sphinx:
  configuration: docs/conf.py
