job_family_map = {
    'surveying and technician of civil and industrial constructions': 'construction',
    'butcher (m/f)': 'other',
    'welder': 'manufacturing',
    'head of large-scale retail trade department': 'other',
    'portal truck driver (m/f)': 'logistics',
    'warehouse worker': 'logistics',
    'general construction worker': 'construction',
    'cnc operator (m/f)': 'manufacturing',
    'nurse': 'healthcare',
    'metalworking worker': 'manufacturing',
    'o.s.s. (operator social health)': 'healthcare',
    'product quality control officer': 'technical',
    'mechanic/toolmaker for welding devices (m/f)': 'manufacturing',
    'construction site technician': 'construction',
    'accounting assistant': 'admin',
    'home appliance assembly worker (m/f)': 'other',
    'molding machine toolmaker (m/f)': 'manufacturing',
    'driver': 'logistics',
    'general manufacturing worker': 'other',
    'assembly worker (m/f)': 'other',
    'maintainer': 'other',
    'packaging clerk (m/f)': 'retail',
    'general service/tertiary worker': 'other',
    'general rubber/plastic worker': 'other',
    'fast food attendant': 'other',
    'store/branch manager': 'retail',
    'hydraulic': 'other',
    'cleaner': 'cleaning/security',
    'warehouse employee': 'logistics',
    'multi-channel customer service operator (sms, web meeting, telephone, email)': 'customer service',
    'industrial designer': 'technical',
    'mechanical designer/mechanical designer': 'technical',
    'chef': 'hospitality',
    'administrative assistant': 'admin',
    'sous chef (m/f)': 'hospitality',
    'purchasing office assistant (m/f)': 'admin',
    'commercial back office': 'customer service',
    'cnc turner': 'manufacturing',
    'waiter ': 'hospitality',
    'store manager': 'retail',
    'administrator of buildings and condominiums': 'other',
    'engineeering project manager': 'other',
    ' chef': 'hospitality',
    'commis of sala': 'other',
    'occupational health and safety coordinator (m/f)': 'cleaning/security',
    'area manager': 'other',
    'general metalworker': 'manufacturing',
    'controller - management control': 'other',
    'production engineer': 'technical',
    'forklift/forklift driver': 'logistics',
    'administrative secretary': 'admin',
    'general food worker': 'other',
    'electrical maintenance worker (m/f)': 'other',
    'laminator (m/f)': 'other',
    'office cleaner (m/f)': 'cleaning/security',
    'general chemical/pharmaceutical worker': 'other',
    'carpenter': 'other',
    'general electronics/electrotechnical worker': 'technical',
    'point of sale clerk/shop assistant': 'admin',
    'mechanical fitter': 'technical',
    'general accounting clerk': 'admin',
    'cnc programmer': 'manufacturing',
    'general energy/extraction worker': 'other',
    'construction engineer': 'construction',
    'technical design manager': 'technical',
    'manual turner': 'other',
    'general textile worker': 'other',
    'personnel administration officer': 'other',
    'mechanic repairer of industrial machines (food industry) (m/f)': 'manufacturing',
    'designer (computer) (m/f)': 'technical',
    'mechanic (road construction machinery) (m/f)': 'construction',
    'order entry / customer service employee': 'customer service',
    'reamer/reamer': 'other',
    'mechanical technician, elettronico, elettrotecnico, microelettronico, elettrico': 'other',
    'electrician': 'other',
    'synthetic grass layer (m/f)': 'other',
    'mechanic maintainer (machines) (m/f)': 'manufacturing',
    'specialized textile worker': 'other',
    'logistics clerk/logistics officer': 'retail',
    'field engineer': 'technical',
    'paper and cardboard production supervisor (m/f)': 'other',
    'general eyewear worker': 'other',
    'electrical design engineer (m/f)': 'technical',
    'warehouse manager': 'logistics',
    'accountant collaborator (m\\f)': 'admin',
    'general paper worker/graphic designer': 'technical',
    'refrigeration engineer': 'technical',
    'delivery boy/delivery girl': 'other',
    'cnc machine operator/cnc machine operator': 'manufacturing',
    'back office employee (m/f)': 'customer service',
    'seller (m/f)': 'other',
    'electromechanical engineer (m/f)': 'technical',
    'body shop': 'retail',
    'stapler/stapler': 'other',
    'pharmaceutical packaging worker': 'other',
    'employee (m/f)': 'other',
    'graphic designer/graphic designer': 'technical',
    'tax center operator': 'other',
    'shelf attendant/shelf attendant': 'other',
    'logistics operations manager (m/f)': 'other',
    'kiln worker (ceramic sector)': 'other',
    'mechanical designer': 'technical',
    'call center operator/call center operator': 'customer service',
    'furniture assembler (m/f)': 'technical',
    'rectifier': 'other',
    'shipping manager (m/f)': 'other',
    'logistics manager': 'other',
    'general automotive worker': 'other',
    'steam and gas turbine operator (m/f)': 'other',
    'sommelier': 'other',
    'installation, repair and maintenance (other) (m/f)': 'other',
    'process engineer': 'technical',
    'robot welder operator (m/f)': 'manufacturing',
    'cnc grinder operator (m/f)': 'manufacturing',
    'front office manager (m/f)': 'other',
    'ict help desk agent': 'customer service',
    'shipping clerk (m/f)': 'retail',
    'commercial employee': 'other',
    'product engineer': 'technical',
    'test driver elettrico': 'logistics',
    'technical sales': 'retail',
    'mechanical design engineer (m/f)': 'technical',
    'bus driver (m/f)': 'logistics',
    'assistant chef (m/f)': 'admin',
    'laundry assistant (m/f)': 'admin',
    'environmental engineer': 'technical',
    'hydraulic help (m/f)': 'other',
    'hostess / ground steward': 'other',
    'test driver': 'logistics',
    'times and methods analyst': 'other',
    'electromechanical traveler (m/f)': 'other',
    'mechanic of window frames, stairs and shutters (m/f)': 'other',
    'quality assurance specialist': 'technical',
    'tax clerk, tax advisor (taxes and taxes)': 'retail',
    'sales associate (shoes and leather goods) (m/f)': 'retail',
    'supermarket clerk (m/f)': 'retail',
    'toy store sales assistant (m/f)': 'admin',
    'purchaser / buyer (m/f)': 'other',
    'customer service technician (m/f)': 'customer service',
    'gastronome': 'other',
    'mechanical toolmaker/mechanical toolmaker': 'manufacturing',
    'b2b commercial': 'other',
    'technical help (m/f)': 'technical',
    'warehouse assistant (m/f)': 'logistics',
    'financial manager': 'other',
    'barman': 'other',
    'supplier accounting clerk': 'admin',
    'risk manager': 'other',
    'planner (m/f)': 'other',
    "electrician's assistant (m/f)": 'admin',
    'human resources administrator (m/f)': 'other',
    'mechanic (light and heavy commercial vehicles) (m/f)': 'other',
    'plc programmer': 'other',
    'technician of prevention in the environment and in the workplace': 'other',
    'site manager (m/f)': 'construction',
    'payroll and contributions officer': 'other',
    'it engineer (m/f)': 'technical',
    'process technologist (m/f)': 'other',
    'management engineer (m/f)': 'technical',
    'continuous wire welder (m/f)': 'manufacturing',
    'specialized tannery/leather worker': 'other',
    'glass processing worker': 'other',
    'warehouse worker with sales functions': 'logistics',
    'sales representative': 'retail',
    'engineer (other) (m/f)': 'technical',
    'general transport/logistics worker': 'other',
    'ramp agent': 'other',
    'automotive mechanic (m/f)': 'other',
    'banker': 'other',
    'reinforced bar fitter worker (m/f)': 'technical',
    'boilermaker': 'other',
    'secretary/secretary': 'admin',
    'single-firm sales agent-representative': 'retail',
    'scientific medical informant/scientific medical informant': 'healthcare',
    'employee - debt collection': 'other',
    'kitchen assistant': 'admin',
    'technical office employee': 'technical',
    'loading/unloading employee': 'other',
    'metrologist': 'other',
    'saldatore tig/elettrico (m/f)': 'other',
    'operations administrator (m/f)': 'other',
    'agent (m/f)': 'other',
    'mechanical technician': 'other',
    'internal controller (m/f)': 'other',
    '3d designer (m/f)': 'technical',
    'overhead crane operator': 'other',
    'beauty consultant': 'other',
    'training and development specialist (m/f)': 'other',
    'document controller': 'other',
    'financial analyst/financial analyst': 'other',
    'sales and commerce (other) (m/f)': 'retail',
    'driver of earthmoving machinery': 'manufacturing',
    'general trade/retail worker': 'other',
    'cashier (m/f)': 'other',
    'assistant project manager (m/f)': 'admin',
    'dental assistant/secretary (m/f)': 'admin',
    'general shoe worker': 'other',
    'swimming pool builder (m/f)': 'other',
    'car mechanic (preparing for sale) (m/f)': 'other',
    'interior designer': 'technical',
    'technician / welder (m/f)': 'manufacturing',
    'woodworking machine operator (m/f)': 'manufacturing',
    'production assistant (m/f)': 'admin',
    'canteen attendant': 'other',
    'painter': 'other',
    'general agriculture/environment/livestock worker': 'other',
    'exterminator (m/f)': 'other',
    'petrol pump attendant / petrol station attendant': 'other',
    'plastic material extrusion worker (m/f)': 'other',
    'tire dealer': 'other',
    'airport attendant': 'other',
    'operator on automatic/semi-automatic machines': 'manufacturing',
    'general ceramics worker': 'other',
    'cnc cutting machine programmer (m/f)': 'manufacturing',
    'general tourist/hotel/catering worker': 'other',
    'technical designer (construction) (m/f)': 'construction',
    'packaging machine operator (m/f)': 'manufacturing',
    'paper printer': 'other',
    'general tannery/leather worker': 'other',
    'administrative assistant in charge of customers (m/f)': 'admin',
    'ecological operator': 'other',
    'air freight operations (m/f)': 'other',
    'machine repair mechanic (m/f)': 'manufacturing',
    'secretary of an advisory committee in public administration (m/f)': 'admin',
    'general aeronautical/maritime/naval worker': 'technical',
    'employee benefits administrative clerk (m/f)': 'admin',
    'driver of bulldozer, caterpillar, bulldozer': 'logistics',
    'road worker (m/f)': 'other',
    'sales clerk in the butchery department': 'retail',
    'delivery driver (m/f)': 'logistics',
    'milling machine': 'manufacturing',
    'model-designer': 'technical',
    'draftsman (electromechanics) (m/f)': 'other',
    'civil electrician (m/f)': 'construction',
    'fiber optic splicer (m/f)': 'other',
    'loader unloader (m/f)': 'other',
    'bartender': 'other',
    'electromechanical fitter/electromechanical fitter': 'technical',
    'single airport operator': 'other',
    'chef de rang': 'hospitality',
    'receptionist (m/f)': 'other',
    'fire safety expert (m/f)': 'cleaning/security',
    'smelter (foundry) (m/f)': 'other',
    'worker in charge of finished leather processing (tannery sector)': 'other',
    'accounting manager': 'admin',
    'cnc milling operator': 'manufacturing',
    'operations assistant (m/f)': 'admin'
}

def map_job_category(category):
    return job_family_map[str.lower(category)]